[package]
name = "wl-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
freedesktop_entry_parser = "1.3.0"
gtk4 = "0.4.8"
xdg = "2.4.1"
