[package]
name = "wl-launcher"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
eframe = "0.19.0"
egui = "0.19.0"
freedesktop_entry_parser = "1.3.0"
